### PR TITLE
Create ZAP Add-on for the scripts

### PR DESCRIPTION
**Pull request by psiinon**
This should do it ;)

The HTML file will be included in the ZAP help and appear on https://www.zaproxy.org/addons/ when its published.
Feel free to add more details in there - I just created a very bare-bones version.

If you add more script types then the gradle file will need tweaking, but we can explain whats needed if/when you get to that stage.

Let me know if you have any questions about any of this.. 

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Added ci.yml

**Comment by psiinon** [comment]
Just realised I've used a package name of `org.zaproxy.addon.sepehrdadscripts` - like me to change that to something like `com.github.sepehrdaddev.scripts`? It can be abything you like really...

**Comment by sepehrdaddev** [comment]
`com.github.sepehrdaddev.zap_scripts` would be super awesome

**Comment by sepehrdaddev** [comment]
I have a question, once the addon is ready, how can I publish it to the market place ?,
I saw that it needs a token from zapbot in the community scripts repo.

**Comment by psiinon** [comment]
We have an issue template for 3rd party add-ons: https://github.com/zaproxy/zaproxy/issues/new?assignees=&labels=marketplace&template=third-party-addon.yml

I'm actually using this as an opourtunity to update our docs, so this should be clearer soon ;)

**Comment by psiinon** [comment]
Updated to use a package name of `com.github.sepehrdaddev.zap_scripts`
@thc202 could you sanity check this again? :)

**Comment by sepehrdaddev** [comment]
awesome, thanks a lot

**Comment by thc202** [comment]
LGTM

**Comment by sepehrdaddev** [comment]
perfect, I will merge

**Pull request merged**
